### ISSUE TITLE
Raspberry Pi 3

### ISSUE THREAD

**Issue by joabakk** [sailoog/openplotter#48]
Is the image rpi3 compatible? I know it only just came out, but has anyone tried it? I tried the sd card from an earlier version, and it was dead in the rpi3

**Comment by sailoog** [comment]
Sometimes yes and sometimes not :)
Some users are experimenting boot issues with openplotter v0.6.0 due to power feeding. It seems that you need provide the required volts. With the new official raspbian image that doesn't happen.
I am building the new openpotter image which will work on RPI 2 and 3. Give some days.

**Comment by antti02210** [comment]
No success w rpi3 here either. Tried running the 0.6 image on rpi2 and upgrading the system, but run into problems with bootloader incompatibilities. Run out of tricks.
Great to know that a new image is brewing!

**Comment by sailoog** [comment]
Read this please: http://www.cruisersforum.com/forums/f13/openplotter-project-152754.html#post2069418

thank you for your patience :)

**Comment by antti02210** [comment]
Great, thank you for the link!
Antti

----- Alkuperäinen viesti -----
Lähettäjä: "Sailoog" <notifications@github.com>
Lähetetty: ‎11.‎3.‎2016 17:25
Vastaanottaja: "sailoog/openplotter" <openplotter@noreply.github.com>
Kopio: "antti02210" <antti.jukarainen@iki.fi>
Aihe: Re: [openplotter] Raspberry Pi 3 (#48)

Read this please: http://www.cruisersforum.com/forums/f13/openplotter-project-152754.html#post2069418
thank you for your patience :)
